### ISSUE TITLE
after system update 1.5.6. rc6 problems

### ISSUE THREAD

**Issue by fvhuizen** [OpenMindNL/ledcollection#3]
After updating the system to 1.5.6. rc6 some options don't work anymore e.g. eyes

**Comment by philsniff** [comment]
yes i can confirm this.
it seems it has to do with the maximum frames for an animation allowed in homey...

**Comment by glijie** [comment]
yep some options stopt working:-)

**Comment by epjjansen-zz** [comment]
the following modes do not work anymore

- Clockwork Colorflow
- Butterfly Colorflow
- Pulsetrain Colorflow
- All the Eyes modes

**Comment by pjmpessers** [comment]
Same here.

**Comment by philsniff** [comment]
eyes works again in homey firmware 1.5.6-rc7! the other animation also? then we can close this issue

**Comment by fvhuizen** [comment]
After the update to r7 issues are solved
